[pytest]
markers =
    smoke: Smoke tests
    regression: Regression tests
    acceptance: Acceptance tests
addopts = -v --strict-markers
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*